### PR TITLE
types: add strong types for all API methods

### LINKED ISSUE #12: Multiple ways to subscribe to streaming RPCs
I just had a realization about how the streaming RPC calls are implemented, which I think should be improved. In the current code, there are two ways implemented to subscribe to events through `lnc-web`:
1. Call the streaming RPC directly via `swapClient.monitor(req, callback, errCallback)`
2. Call `loop.connectStreams()` to subscribe followed by `loop.on('status', callback)` to provide the callback

Do you think we should remove one of these way to subscribe since it's a bit redundant and may cause confusion for users?

My suggestion would be to remove the second method because we would need to subscribe to all streams available when calling `connectStreams`. This is not a big issue for Loop which only has one streaming RPC. But for LND, there are many. Currently in [LndApi.connectStreams](https://github.com/lightninglabs/lnc-web/blob/main/lib/api/lnd/index.ts#L236), we only subscribe to three RPCs, but this makes it impossible for the user to receive `subscribeChannelBackups` events using this method. In order to make this possible, we would need to subscribe to all LND streaming RPCs when `connectStreams` is called. This would make the browser receive all of the events, even the ones that the user has no interest in. Another downside to this approach is that you cannot subscribe to the one-off streaming RPCs like `closeChannel` and `subscribeSingleInvoice` via `connectStreams` because they require parameters to be supplied. 

What do you think about how to handle these subscriptions?

### PR DESCRIPTION
**Pull request by jamaljsr**
This PR replaces the existing [@improbable-eng/grpc-web](https://github.com/improbable-eng/grpc-web) generated TS/JS files with types generated by the [ts-proto](https://github.com/stephenh/ts-proto) protoc plugin. The new plugin comes with a few benefits:
- eliminates the JS implementation files which reduces the bundle size from 2.1MB to 146KB
- the types match exactly with the request & response objects the WASM produces. I needed to do a bit of post-processing on the generated TS files, but this is a one-time effort that won't require any ongoing maintenance when the protos are updated
- due to the above, we no longer need to hack the request & response objects to match the types
- the new types are cleaner. We no longer need to have `*.AsObject` littered throughout the app's codebase

In addition to updating the types, I also refactored the API classes to only use callbacks for the subscription methods, removing the `EventEmitter` functions since they were redundant (closes #12). I also deleted a bunch of files and dependencies that were no longer being used.

### CODE REVIEW

**Comment by jamaljsr** [comment]
I figured out a solution to shortening up the import paths. It required a small webpack plugin and updates to to the `package.json`. Apps can now import the generated types using:
```ts
import { SwapStatus } from '@lightninglabs/lnc-web/looprpc';
import { Transaction } from '@lightninglabs/lnc-web/lnrpc';
```

**Comment by jamaljsr** [comment]
Hold on merging this, I need to investigate an issue in the latest commits.

**Comment by jamaljsr** [comment]
Ok, I cudn't get the import paths above to work without randomly causing a weird infinite loop when apps import using those paths. I was able to get it working under a slightly less ideal method, but still better than the super long paths.
```ts
import { looprpc } from '@lightninglabs/lnc-web';
const status: looprpc.SwapStatus = { ... };
```

This is good to go for a final review now.

**Comment by kaloudis** [comment]
tACK 🚀

**Pull request merged**
